<font color=Green>
    
# **3.6 Fechas con pandas**

</font>

### Pandas también incluye sus propias funciones para trabajar con fechas.

In [1]:
import numpy as np
import pandas as pd
import datetime

## <font color=#003d5c>_.to_datetime()_ </font>

In [3]:
fecha = pd.to_datetime('14th July, 2022')

print(fecha)
print(type(fecha))

2022-07-14 00:00:00
<class 'pandas._libs.tslibs.timestamps.Timestamp'>

In [ ]:
fecha.hour, fecha.minute, fecha.second

## <font color=#003d5c>_.to_timedelta()_ </font>
### Esta función nos permite calcular los días antes o después de una fecha determinada.

In [4]:
fecha = datetime.datetime.now()

print(fecha)

2022-07-14 13:45:17.973044

### La fecha del día siguiente

In [5]:
print('La fecha de hoy es: ', fecha)

print('Y la fecha en 4 días será: ', fecha + pd.to_timedelta(4,unit='D'))

La fecha de hoy es:  2022-07-14 13:45:17.973044
Y la fecha en 4 días será:  2022-07-18 13:45:17.973044

## <font color=#003d5c>_.date_range()_ </font>
### Este método nos permite generar un rango de fechas.

In [6]:
fechas_inicio = pd.date_range(start='14/4/2022', end='14/8/2022', freq='D')
fechas_inicio

DatetimeIndex(['2022-04-14', '2022-04-15', '2022-04-16', '2022-04-17',
               '2022-04-18', '2022-04-19', '2022-04-20', '2022-04-21',
               '2022-04-22', '2022-04-23',
               ...
               '2022-08-05', '2022-08-06', '2022-08-07', '2022-08-08',
               '2022-08-09', '2022-08-10', '2022-08-11', '2022-08-12',
               '2022-08-13', '2022-08-14'],
              dtype='datetime64[ns]', length=123, freq='D')

In [9]:
fechas_fin = pd.date_range(start='24/5/2020', end='24/6/2020', freq='D')
fechas_fin

DatetimeIndex(['2020-05-24', '2020-05-25', '2020-05-26', '2020-05-27',
               '2020-05-28', '2020-05-29', '2020-05-30', '2020-05-31',
               '2020-06-01', '2020-06-02', '2020-06-03', '2020-06-04',
               '2020-06-05', '2020-06-06', '2020-06-07', '2020-06-08',
               '2020-06-09', '2020-06-10', '2020-06-11', '2020-06-12',
               '2020-06-13', '2020-06-14', '2020-06-15', '2020-06-16',
               '2020-06-17', '2020-06-18', '2020-06-19', '2020-06-20',
               '2020-06-21', '2020-06-22', '2020-06-23', '2020-06-24'],
              dtype='datetime64[ns]', freq='D')

In [10]:
lista_equis = []

for i in range(15):
    lista_equis.append(np.random.randint(2))


df = pd.DataFrame()

df['Inicio_campaña'] = fechas_inicio[:15]
df['Fin_campaña'] = fechas_fin[:15]
df['Target'] = lista_equis

df

   Inicio_campaña Fin_campaña  Target
0      2022-04-14  2020-05-24       0
1      2022-04-15  2020-05-25       1
2      2022-04-16  2020-05-26       1
3      2022-04-17  2020-05-27       1
4      2022-04-18  2020-05-28       0
5      2022-04-19  2020-05-29       1
6      2022-04-20  2020-05-30       0
7      2022-04-21  2020-05-31       0
8      2022-04-22  2020-06-01       0
9      2022-04-23  2020-06-02       1
10     2022-04-24  2020-06-03       0
11     2022-04-25  2020-06-04       0
12     2022-04-26  2020-06-05       1
13     2022-04-27  2020-06-06       0
14     2022-04-28  2020-06-07       1

In [11]:
df['Día de inicio'] = df['Inicio_campaña'].dt.day


df['Mes de inicio'] = df['Inicio_campaña'].dt.month


df['Año de inicio'] = df['Inicio_campaña'].dt.year


df['Hora_inicio'] = df['Inicio_campaña'].dt.hour


df['Minuto_inicio'] = df['Inicio_campaña'].dt.minute


df['Segundo_inicio'] = df['Inicio_campaña'].dt.second


df['Nombre del día de inicio'] = df['Inicio_campaña'].dt.weekday


df['Semana del año de inicio'] = df['Inicio_campaña'].dt.week


df['Duración'] = df['Fin_campaña']-df['Inicio_campaña']

C:\Users\RONALD~1\AppData\Local\Temp/ipykernel_10836/254327194.py:22: FutureWarning: Series.dt.weekofyear and Series.dt.week have been deprecated.  Please use Series.dt.isocalendar().week instead.
  df['Semana del año de inicio'] = df['Inicio_campaña'].dt.week

In [12]:
df.columns = ['Inicio_campaña', 'Fin_campaña', 'Target','Día de inicio','Mes de inicio','Año de inicio','Hora_inicio',
              'Minuto_inicio','Segundo_inicio','Día de la semana del inicio','Semana del año de inicio','Duración']

In [13]:
df

,Inicio_campaña,Fin_campaña,Target,Día de inicio,Mes de inicio,Año de inicio,Hora_inicio,Minuto_inicio,Segundo_inicio,Día de la semana del inicio,Semana del año de inicio,Duración
0,2022-04-14,2020-05-24,0,14,4,2022,0,0,0,3,15,-690 days
1,2022-04-15,2020-05-25,1,15,4,2022,0,0,0,4,15,-690 days
2,2022-04-16,2020-05-26,1,16,4,2022,0,0,0,5,15,-690 days
3,2022-04-17,2020-05-27,1,17,4,2022,0,0,0,6,15,-690 days
4,2022-04-18,2020-05-28,0,18,4,2022,0,0,0,0,16,-690 days
5,2022-04-19,2020-05-29,1,19,4,2022,0,0,0,1,16,-690 days
6,2022-04-20,2020-05-30,0,20,4,2022,0,0,0,2,16,-690 days
7,2022-04-21,2020-05-31,0,21,4,2022,0,0,0,3,16,-690 days
8,2022-04-22,2020-06-01,0,22,4,2022,0,0,0,4,16,-690 days
9,2022-04-23,2020-06-02,1,23,4,2022,0,0,0,5,16,-690 days
10,2022-04-24,2020-06-03,0,24,4,2022,0,0,0,6,16,-690 days
11,2022-04-25,2020-06-04,0,25,4,2022,0,0,0,0,17,-690 days
12,2022-04-26,2020-06-05,1,26,4,2022,0,0,0,1,17,-690 days
13,2022-04-27,2020-06-06,0,27,4,2022,0,0,0,2,17,-690 days
14,2022-04-28,2020-06-07,1,28,4,2022,0,0,0,3,17,-690 days

In [14]:
from datetime import timedelta

df['Días de duración'] = df['Duración']/timedelta(days=1)

df['Minutos de duración'] = df['Duración']/timedelta(minutes=1)

df['Segundos de duración'] = df['Duración']/timedelta(seconds=1)

df

,Inicio_campaña,Fin_campaña,Target,Día de inicio,Mes de inicio,Año de inicio,Hora_inicio,Minuto_inicio,Segundo_inicio,Día de la semana del inicio,Semana del año de inicio,Duración,Días de duración,Minutos de duración,Segundos de duración
0,2022-04-14,2020-05-24,0,14,4,2022,0,0,0,3,15,-690 days,-690.0,-993600.0,-59616000.0
1,2022-04-15,2020-05-25,1,15,4,2022,0,0,0,4,15,-690 days,-690.0,-993600.0,-59616000.0
2,2022-04-16,2020-05-26,1,16,4,2022,0,0,0,5,15,-690 days,-690.0,-993600.0,-59616000.0
3,2022-04-17,2020-05-27,1,17,4,2022,0,0,0,6,15,-690 days,-690.0,-993600.0,-59616000.0
4,2022-04-18,2020-05-28,0,18,4,2022,0,0,0,0,16,-690 days,-690.0,-993600.0,-59616000.0
5,2022-04-19,2020-05-29,1,19,4,2022,0,0,0,1,16,-690 days,-690.0,-993600.0,-59616000.0
6,2022-04-20,2020-05-30,0,20,4,2022,0,0,0,2,16,-690 days,-690.0,-993600.0,-59616000.0
7,2022-04-21,2020-05-31,0,21,4,2022,0,0,0,3,16,-690 days,-690.0,-993600.0,-59616000.0
8,2022-04-22,2020-06-01,0,22,4,2022,0,0,0,4,16,-690 days,-690.0,-993600.0,-59616000.0
9,2022-04-23,2020-06-02,1,23,4,2022,0,0,0,5,16,-690 days,-690.0,-993600.0,-59616000.0
10,2022-04-24,2020-06-03,0,24,4,2022,0,0,0,6,16,-690 days,-690.0,-993600.0,-59616000.0
11,2022-04-25,2020-06-04,0,25,4,2022,0,0,0,0,17,-690 days,-690.0,-993600.0,-59616000.0
12,2022-04-26,2020-06-05,1,26,4,2022,0,0,0,1,17,-690 days,-690.0,-993600.0,-59616000.0
13,2022-04-27,2020-06-06,0,27,4,2022,0,0,0,2,17,-690 days,-690.0,-993600.0,-59616000.0
14,2022-04-28,2020-06-07,1,28,4,2022,0,0,0,3,17,-690 days,-690.0,-993600.0,-59616000.0